### PR TITLE
fix: don't keepalive when the connection is busy

### LINKED ISSUE #15: Connections cut under heavy load
Under heavy load, yamux connections fail to ping fast enough and get cut. We should just stop pinging when we're under load (because we _know_ the peer is alive).

### PR DESCRIPTION
**Pull request by Stebalien**
* It's a waste of bandwidth.
* It causes us to think the connection is dead because the other side is too busy sending us _other_ data to respond to the ping.

fixes #15

### CODE REVIEW

File: session.go [hunk 1]
```diff
@@ -506,6 +508,14 @@ func (s *Session) recvLoop() error {
 			return err
 		}
 
+		// Reset the keepalive timer every time we receive data.
+		// There's no reason to keepalive if we're active. Worse, if the
+		// peer is busy sending us stuff, the pong might get stuck
+		// behind a bunch of data.
+		if s.keepaliveTimer != nil {
+			s.keepaliveTimer.Reset(s.config.KeepAliveInterval)
```
Comment (Stebalien) [inline session.go]: This is the bugfix.

Comment (marten-seemann) [reply session.go]: Don't you need to check if the timer has already been read as described in https://golang.org/pkg/time/#Timer.Reset?

Comment (vyzo) [reply session.go]: this one gets me every time too -- the API for resetting timers is really poor.

Comment (Stebalien) [reply session.go]: Not in this case. Reset actually stops it internally.

You have to stop it first and drain the channel if you want to make sure that the previous timer doesn't fire after you reset it but before new timeout elapses. However:

1. We don't _really_ care in this case.
2. This isn't a normal timer, it's an AfterFunc and doesn't have a channel to drain. There's no way to reliably stop an AfterFunc because the function is called asynchronously. Note: trying to drain a channel of a timer created by `AfterFunc` will just block forever.
